import { test, expect } from "../fixtures/auth.fixture";
import { navigateViaNav, waitForLoad } from "../helpers/selectors";
function getCurrentWeekDates() {
  const now = new Date;
  const day = now.getDay();
  const diffToMonday = day === 0 ? -6 : 1 - day;
  const monday = new Date(now);
  monday.setDate(now.getDate() + diffToMonday);
  const friday = new Date(monday);
  friday.setDate(monday.getDate() + 4);
  const fmt = (d) => `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
  return { startDate: fmt(monday), endDate: fmt(friday) };
}
test.describe("Export", () => {
  test("export Excel file downloads via POST", async ({ authenticatedPage: page }) => {
    await navigateViaNav(page, "Export");
    await page.waitForURL("**/export");
    await waitForLoad(page);
    await expect(page.getByText("Export Timesheet")).toBeVisible();
    const { startDate, endDate } = getCurrentWeekDates();
    await page.locator('input[type="date"]').first().fill(startDate);
    await page.locator('input[type="date"]').last().fill(endDate);
    const requestPromise = page.waitForRequest((req) => req.url().includes("/export/excel") && req.method() === "POST");
    const downloadPromise = page.waitForEvent("download", { timeout: 15000 });
    await page.getByRole("button", { name: "Download" }).click();
    const request = await requestPromise;
    expect(request.method()).toBe("POST");
    const postBody = request.postDataJSON();
    expect(postBody.startDate).toBe(startDate);
    expect(postBody.endDate).toBe(endDate);
    expect(postBody).toHaveProperty("descriptionOverrides");
    const download = await downloadPromise;
    expect(download.suggestedFilename()).toContain("timesheet");
    expect(download.suggestedFilename()).toContain(".xlsx");
    await expect(page).toHaveURL(/\/export/);
  });
  test("export PDF file downloads via POST", async ({ authenticatedPage: page }) => {
    await navigateViaNav(page, "Export");
    await page.waitForURL("**/export");
    await waitForLoad(page);
    await page.getByLabel("Format").locator("..").click();
    await page.getByRole("option", { name: "PDF" }).click();
    const { startDate, endDate } = getCurrentWeekDates();
    await page.locator('input[type="date"]').first().fill(startDate);
    await page.locator('input[type="date"]').last().fill(endDate);
    const requestPromise = page.waitForRequest((req) => req.url().includes("/export/pdf") && req.method() === "POST");
    const downloadPromise = page.waitForEvent("download", { timeout: 15000 });
    await page.getByRole("button", { name: "Download" }).click();
    const request = await requestPromise;
    expect(request.method()).toBe("POST");
    const download = await downloadPromise;
    expect(download.suggestedFilename()).toContain("timesheet");
    expect(download.suggestedFilename()).toContain(".pdf");
    await expect(page).toHaveURL(/\/export/);
  });
  test("preview table appears when dates are filled", async ({ authenticatedPage: page }) => {
    await navigateViaNav(page, "Export");
    await page.waitForURL("**/export");
    await waitForLoad(page);
    const { startDate, endDate } = getCurrentWeekDates();
    await page.locator('input[type="date"]').first().fill(startDate);
    await page.locator('input[type="date"]').last().fill(endDate);
    const dataTable = page.locator(".v-data-table");
    await expect(dataTable).toBeVisible({ timeout: 1e4 });
    const headers = dataTable.locator("th");
    await expect(headers.nth(0)).toContainText("Date");
    await expect(headers.nth(1)).toContainText("Start");
    await expect(headers.nth(2)).toContainText("End");
    await expect(headers.nth(3)).toContainText("Hours");
    await expect(headers.nth(4)).toContainText("Project");
    await expect(headers.nth(5)).toContainText("Ticket");
    await expect(headers.nth(6)).toContainText("Summary");
    await expect(headers.nth(7)).toContainText("Description");
    const rows = dataTable.locator("tbody tr");
    await expect(rows.first()).toBeVisible();
    expect(await rows.count()).toBeGreaterThan(0);
  });
  test("description can be overridden in preview table", async ({ authenticatedPage: page }) => {
    await navigateViaNav(page, "Export");
    await page.waitForURL("**/export");
    await waitForLoad(page);
    const { startDate, endDate } = getCurrentWeekDates();
    await page.locator('input[type="date"]').first().fill(startDate);
    await page.locator('input[type="date"]').last().fill(endDate);
    const dataTable = page.locator(".v-data-table");
    await expect(dataTable).toBeVisible({ timeout: 1e4 });
    const firstRowDescInput = dataTable.locator("tbody tr").first().locator("input").last();
    await expect(firstRowDescInput).toBeVisible();
    await firstRowDescInput.fill("My custom override description");
    await expect(firstRowDescInput).toHaveValue("My custom override description");
  });
});
