import { test, expect } from "../fixtures/auth.fixture";
import { navigateViaNav, waitForLoad } from "../helpers/selectors";
test.describe("Tickets", () => {
  test("list tickets for project", async ({ authenticatedPage: page }) => {
    await navigateViaNav(page, "Tickets");
    await page.waitForURL("**/admin/tickets");
    await waitForLoad(page);
    await page.getByRole("combobox", { name: "Project" }).click({ force: true });
    await page.getByRole("option", { name: /PCLASS/ }).click();
    await page.keyboard.press("Escape");
    await page.waitForLoadState("networkidle");
    await expect(page.getByText("PCLASS-101")).toBeVisible();
    await expect(page.getByText("PCLASS-102")).toBeVisible();
  });
  test("create ticket", async ({ authenticatedPage: page }) => {
    await navigateViaNav(page, "Tickets");
    await page.waitForURL("**/admin/tickets");
    await waitForLoad(page);
    await page.getByRole("combobox", { name: "Project" }).click({ force: true });
    await page.getByRole("option", { name: /PCLASS/ }).click();
    await page.keyboard.press("Escape");
    await page.waitForLoadState("networkidle");
    await page.getByRole("button", { name: "Create Ticket" }).click();
    const dialog = page.locator(".v-dialog");
    await expect(dialog).toBeVisible();
    await dialog.getByLabel("Summary").fill("New test ticket for E2E");
    await dialog.getByLabel("Estimated Hours").fill("4");
    await dialog.getByRole("button", { name: "Save" }).click();
    await expect(dialog).toBeHidden({ timeout: 5000 });
    await expect(page.getByText("New test ticket for E2E").first()).toBeVisible();
  });
  test("edit ticket status", async ({ authenticatedPage: page }) => {
    await navigateViaNav(page, "Tickets");
    await page.waitForURL("**/admin/tickets");
    await waitForLoad(page);
    await page.getByRole("combobox", { name: "Project" }).click({ force: true });
    await page.getByRole("option", { name: /PCLASS/ }).click();
    await page.keyboard.press("Escape");
    await page.waitForLoadState("networkidle");
    const editBtn = page.locator(".v-data-table tbody tr").first().locator("button:has(.mdi-pencil)").first();
    await editBtn.click();
    const dialog = page.locator(".v-dialog");
    await expect(dialog).toBeVisible();
    await dialog.getByLabel("Status").click({ force: true });
    await page.getByRole("option", { name: "done" }).click();
    const hoursField = dialog.getByLabel("Estimated Hours");
    await hoursField.clear();
    await hoursField.fill("2");
    await dialog.getByRole("button", { name: "Save" }).click();
    await expect(dialog).toBeHidden({ timeout: 5000 });
    await expect(page.locator(".v-data-table").getByText("Done").first()).toBeVisible();
  });
  test("multi-select projects with select all / deselect all", async ({ authenticatedPage: page }) => {
    await navigateViaNav(page, "Tickets");
    await page.waitForURL("**/admin/tickets");
    await waitForLoad(page);
    const openDropdown = async () => {
      await page.locator(".v-select .v-field__append-inner").first().click();
      await page.waitForTimeout(300);
    };
    await openDropdown();
    await page.getByText("Select All").click();
    await page.keyboard.press("Escape");
    await page.waitForLoadState("networkidle");
    await expect(page.getByText("PCLASS-101")).toBeVisible();
    await expect(page.getByRole("button", { name: "Create Ticket" })).toBeDisabled();
    await openDropdown();
    await page.getByText("Deselect All").click({ force: true });
    await page.keyboard.press("Escape");
    await page.waitForLoadState("networkidle");
    await expect(page.getByText("PCLASS-101")).toBeHidden();
    await openDropdown();
    await page.getByRole("option", { name: /PCLASS/ }).click();
    await page.keyboard.press("Escape");
    await page.waitForLoadState("networkidle");
    await expect(page.getByRole("button", { name: "Create Ticket" })).toBeEnabled();
  });
});
